name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  test-standing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test at Standing
        id: test-standing
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}
      - run: ssh ${{ steps.test-standing.outputs.SERVER }} bash /app/deploy.sh moka_sasaki

  deploy-production:
    runs-on: ubuntu-latest
    needs: test-standing 
    steps:
      - name: Deploy to Production
        id: deploy-production
        uses: invi5H/ssh-action@v1
        if: success() 
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSHE_SSH_KEY }}
      - run: |
          # スクリプトのパスを設定
          SCRIPT_PATH="/app/deploy.sh"
          # ユーザー名を設定
          USER_NAME="moka_sasaki"
          # スクリプトをリモートホストで実行
          ssh ${{ steps.deploy-production.outputs.SERVER }} bash $SCRIPT_PATH $USER_NAME
