name: CI/CD Workflow

on:
  push:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install NPM dependencies
        run: npm install

      - name: Set Working Directory
        run: cd /app/moka_sasaki

      - name: Cypress run
        env:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}
          working-directory: /ci
        run: npx cypress run --browser chrome --spec cypress/e2e/moka_sasaki.*

      - name: Deploy to Production
        if: success() # Only deploy to Production if the previous steps were successful
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSHE_SSH_KEY }}
        run: |
          # Deploy to Production environment using /app/deploy.sh
          bash /app/deploy.sh moka_sasaki
