name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test at Standing
        id: test-standing
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}
      - run: ssh ${{ steps.test-standing.outputs.SERVER }} bash /app/deploy.sh moka_sasaki

      - name: Deploy to Production
        id: deploy-production
        uses: invi5H/ssh-action@v1
        if: success() # Only deploy to Production if the previous steps were successful
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSHE_SSH_KEY }}
      - run: ssh ${{ steps.deploy-production.outputs.SERVER }} bash /app/deploy.sh moka_sasaki
